
//Uncomment one of these
//#define LASER_ACTIVATED_ADLIAS_BLOWER_GUN (1)
//#define LASER_ACTIVATED_FOG_GUN (1)
//#define LASER_ACTIVATED_WATER_GUN (1)
//#define LASER_ACTIVATED_BUBBLE_GUN (1)
//#define LASER_ACTIVATED_EAGLE_GUN  (1)
#define LASER_ACTIVATED_GOKART_GUN (1)
